In [8]:
import numpy as np

### Задание 1

In [3]:
a = np.array([[1, 6],[2, 8], [3,11],[3,10],[1,7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean_a = a.mean(axis=0)

In [12]:
mean_a

array([2. , 8.4])

### Задание 2

In [13]:
a_centered = np.subtract(a, mean_a)

In [14]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### 3

In [15]:
a1 = a_centered[:,0]

In [16]:
a1

array([-1.,  0.,  1.,  1., -1.])

In [17]:
a2 = a_centered[:,1]

In [18]:
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [19]:
a_centered_sp = np.dot(a1,a2)

In [20]:
a_centered_sp

8.0

In [21]:
a_centered_sp = a_centered_sp / 4

In [22]:
a_centered_sp

2.0

### 4

In [23]:
a_t = a.T

In [24]:
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [25]:
c = np.cov(a_t)

In [26]:
c

array([[1. , 2. ],
       [2. , 4.3]])

PD 1

In [1]:
import pandas as pd

In [4]:
authors = pd.DataFrame({"author_id": [1, 2, 3], "author": ['Тургенев', 'Чехов', 'Островский']})

In [6]:
authors

author_id      author
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [7]:
book = pd.DataFrame({"author_id": [1, 1, 1, 2, 2, 3, 3], "book_title":
                     ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     "price": [100, 100, 100, 200, 200, 300, 300]})

In [8]:
book

author_id            book_title  price
0          1           Отцы и дети    100
1          1                 Рудин    100
2          1     Дворянское гнездо    100
3          2      Толстый и тонкий    200
4          2       Дама с собачкой    200
5          3                 Гроза    300
6          3  Таланты и поклонники    300

### 2

In [12]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')

In [13]:
authors_price

author_id      author            book_title  price
0          1    Тургенев           Отцы и дети    100
1          1    Тургенев                 Рудин    100
2          1    Тургенев     Дворянское гнездо    100
3          2       Чехов      Толстый и тонкий    200
4          2       Чехов       Дама с собачкой    200
5          3  Островский                 Гроза    300
6          3  Островский  Таланты и поклонники    300

### 3

In [14]:
top5=authors_price.nlargest(5, 'price')

In [15]:
top5

author_id      author            book_title  price
5          3  Островский                 Гроза    300
6          3  Островский  Таланты и поклонники    300
3          2       Чехов      Толстый и тонкий    200
4          2       Чехов       Дама с собачкой    200
0          1    Тургенев           Отцы и дети    100

#### 

### 4

In [20]:
p1 = authors_price.groupby('author').agg({'price': 'min'}).rename(columns={'price':'min_price'})

In [21]:
p2 = authors_price.groupby('author').agg({'price': 'max'}).rename(columns={'price':'max_price'})

In [22]:
p3 = authors_price.groupby('author').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})

In [23]:
authors_stat=pd.concat([p1, p2, p3], axis = 1)

In [24]:
authors_stat

min_price  max_price  mean_price
author                                      
Островский        300        300       300.0
Тургенев          100        100       100.0
Чехов             200        200       200.0