In [8]:
import numpy as np

### Задание 1

In [3]:
a = np.array([[1, 6],[2, 8], [3,11],[3,10],[1,7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean_a = a.mean(axis=0)

In [12]:
mean_a

array([2. , 8.4])

### Задание 2

In [13]:
a_centered = np.subtract(a, mean_a)

In [14]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### 3

In [15]:
a1 = a_centered[:,0]

In [16]:
a1

array([-1.,  0.,  1.,  1., -1.])

In [17]:
a2 = a_centered[:,1]

In [18]:
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [19]:
a_centered_sp = np.dot(a1,a2)

In [20]:
a_centered_sp

8.0

In [21]:
a_centered_sp = a_centered_sp / 4

In [22]:
a_centered_sp

2.0

### 4

In [23]:
a_t = a.T

In [24]:
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [25]:
c = np.cov(a_t)

In [26]:
c

array([[1. , 2. ],
       [2. , 4.3]])